config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  get "short_code_resolver/resolve/:collection_code/:work_code" => "short_code_resolver#resolve"
  get "application_status" => "status#application_status"

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :custom_report_templates
  get "tags.json" => "application#tags"
  get "geoname_summaries.json" => "application#geoname_summaries"

  resources :reminders
  resources :stages
  get "offline/work_form"

  get "offline/offline"

  get "offline/collections"

  get "offline/collection"

  get "scan" => "scan#show"

  namespace :api do
    namespace :v1 do
      resources :time_spans, only: [:index, :show]
      resources :works, only: [:show]
      resources :work_sets, only: [:show]
      resources :collections, only: [:index, :show] do
        resources :works, only: [:index, :show] do
          resources :work_events, only: [:create]
        end
      end
    end
  end

  resources :messages do
    get "new_reply" => "messages#new"
  end
  devise_for :users, controllers: {
    confirmation: "confirmation",
    registrations: "registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }
  resources :users, only: [:index, :edit, :update, :destroy]
  get "users/oauth"

  resources :conditions
  resources :currencies
  resources :damage_types
  resources :frame_damage_types
  resources :frame_types
  resources :media
  resources :object_categories
  resources :placeabilities
  resources :sources
  resources :subsets
  resources :techniques
  resources :themes
  resources :balance_categories
  resources :work_statuses
  resources :work_sets do
    resources :works, module: :work_sets, only: :destroy # , controller: "WorkSet::WorksController"
  end
  resources :work_set_types

  resources :rkd_artists, module: :r_k_d, controller: :artists do
    patch "copy" => "rkd_artists#copy"
  end

  resources :works do
    resources :attachments
  end

  resources :involvements
  resources :collections do
    get "manage" => "collections#manage"
    resources :contacts
    resources :locations
    resources :users, module: :collection
    resources :labels, module: :collection
    resources :library_items
    resources :time_spans, only: [:index, :show]

    resources :work_sets do
      resources :appraisals
      resources :time_spans
    end

    resources :reminders, path: "manage/reminders"
    resources :themes, path: "manage/themes"
    resources :clusters
    resources :import_collections, path: "manage/import_collections" do
      get "preview" => "import_collections#preview"
      patch "delete_works" => "import_collections#delete_works"
      patch "import_works" => "import_collections#import_works"
    end

    resources :simple_import_collections, path: "manage/simple_import_collections" do
      get "preview" => "simple_import_collections#preview"
      patch "import_works" => "simple_import_collections#import_works"
    end

    resources :owners
    resources :custom_reports, path: "manage/custom_reports"

    resources :attachments
    resources :collections_stages
    resources :messages
    post "refresh_works" => "collections#refresh_works"
    resources :collections do
    end
    resources :batch_photo_uploads do
      post "match_works" => "batch_photo_uploads#match_works"
    end
    resources :artists do
      get :collectie_nederland_summary

      get "combine_prepare" => "artists#combine_prepare"
      patch "combine" => "artists#combine"

      resources :rkd_artists, module: :r_k_d, controller: :artists
      resources :artist_involvements
      resources :attachments
      resources :library_items
    end
    resources :rkd_artists, module: :r_k_d, controller: :artists do
      patch "copy" => "rkd_artists#copy"
    end

    get "works/modified" => "works#modified_index"

    get "batch" => "batch#show"
    post "batch" => "batch#show"
    patch "batch" => "batch#update"

    get "mobile" => "mobiles#show"
    patch "mobile" => "mobiles#update"

    resources :works do
      resources :attachments
      resources :appraisals
      resources :messages
      resources :library_items
      resources :time_spans
      get "old_data" => "works#show_old_data"
      get "edit_prices" => "works#edit_prices"
      get "location_history" => "works#location_history"
      get "edit_location" => "works#edit_location"
      get "edit_tags" => "works#edit_tags"
      get "edit_photos" => "works#edit_photos"
    end

    get "report" => "report#show"
    get "stats" => "stats#show"
  end
  resources :artists do
    get :collectie_nederland_summary
    patch "collectie_nederland_summary" => "artists#collectie_nederland_summary_update"
    get "combine_prepare" => "artists#combine_prepare"
    patch "combine" => "artists#combine"
    resources :rkd_artists, module: :r_k_d, controller: :artists
    get "old_data" => "artists#show_old_data"

    resources :artist_involvements
  end
  post "/artists/clean" => "artists#clean"

  resources :professional_activities

  get "debug-offline" => "application#debug_offline"

  get "admin", to: Admin::AdminController.action(:index)

  namespace :admin do
    resources :o_auth_group_mappings
  end
  get "sw" => "application#service_worker"
  get "style-guide" => "application#style_guide"
  root "application#home"

end

app/models/collection.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: collections
#
#  id                                        :bigint           not null, primary key
#  appraise_with_ranges                      :boolean          default(FALSE)
#  base                                      :boolean
#  collection_name_extended_cache            :text
#  commercial                                :boolean
#  default_collection_attributes_for_artists :text             default(["\"website\"", "\"email\"", "\"telephone_number\"", "\"description\""]), is an Array
#  default_collection_attributes_for_works   :text             default([]), is an Array
#  derived_work_attributes_present_cache     :text
#  description                               :text
#  exposable_fields                          :text
#  external_reference_code                   :string
#  geoname_ids_cache                         :text
#  internal_comments                         :text
#  label_override_work_alt_number_1          :string
#  label_override_work_alt_number_2          :string
#  label_override_work_alt_number_3          :string
#  name                                      :string
#  qkunst_managed                            :boolean          default(TRUE)
#  root                                      :boolean          default(FALSE)
#  show_availability_status                  :boolean
#  show_library                              :boolean
#  sort_works_by                             :string
#  supported_languages                       :text             default(["\"nl\""]), is an Array
#  unique_short_code                         :string
#  work_attributes_present_cache             :text
#  created_at                                :datetime         not null
#  updated_at                                :datetime         not null
#  parent_collection_id                      :bigint           default(1)
#
# Indexes
#
#  index_collections_on_unique_short_code  (unique_short_code) UNIQUE
#

class Collection < ApplicationRecord
  include MethodCache
  include Collection::Hierarchy

  class CollectionBaseError < StandardError
  end

  class FakeSuperCollection
    def name
      "Algemeen"
    end

    def themes
      Theme.general
    end

    def not_hidden_themes
      themes.not_hidden
    end
  end

  belongs_to :parent_collection, class_name: "Collection", optional: true

  has_and_belongs_to_many :users
  has_and_belongs_to_many :stages

  has_many :attachments
  has_many :batch_photo_uploads
  has_many :child_collections, class_name: "Collection", foreign_key: "parent_collection_id"
  has_many :clusters
  has_many :collections, class_name: "Collection", foreign_key: "parent_collection_id"
  has_many :collections_geoname_summaries
  has_many :collection_attributes
  has_many :custom_reports
  has_many :geoname_summaries, through: :collections_geoname_summaries
  has_many :import_collections
  has_many :simple_import_collections
  has_many :themes
  has_many :works
  has_many :owners
  has_many :messages, as: :subject_object
  has_many :collections_stages
  has_many :reminders
  has_many :library_items
  has_many :locations
  has_many :time_spans
  has_many :contacts

  validates_uniqueness_of :unique_short_code, allow_nil: true

  has_cache_for_method :geoname_ids, trigger: :before_save
  has_cache_for_method :collection_name_extended
  has_cache_for_methods :work_attributes_present, :derived_work_attributes_present, as: :symbols, trigger: :before_save

  has_paper_trail # only enabled in may 2020

  default_scope -> { order(Arel.sql("REPLACE(collections.collection_name_extended_cache, '\"', '') ASC")) }

  scope :without_parent, -> { where(parent_collection_id: nil) }
  scope :not_hidden, -> { where("1=1") }
  scope :not_system, -> { not_root }
  scope :qkunst_managed, -> { where(qkunst_managed: true) }

  before_save :attach_sub_collection_ownables_when_base

  after_create :copy_default_reminders!
  after_save :touch_works_including_child_works!
  after_save :cache_all_collection_name_extended!

  after_commit :touch_parent

  KEY_MODEL_RELATIONS = {
    "artists" => "Artist",
    "themes" => "Theme",
    "object_categories" => "ObjectCategory",
    "object_categories_split" => "ObjectCategory",
    "techniques" => "Technique",
    "condition_frame" => "Condition",
    "techniques_split" => "Technique",
    "condition_work" => "Condition",
    "frame_damage_types" => "FrameDamageType",
    "damage_types" => "DamageType",
    "placeability" => "Placeability",
    "balance_category" => "BalanceCategory",
    "style" => "Style",
    "subset" => "Subset",
    "source" => "Source",
    "sources" => "Source",
    "cluster" => "Cluster",
    "owner" => "Owner",
    "frame_type" => "FrameType",
    "work_status" => "WorkStatus",
    "work_sets" => "WorkSet",
    "collection_attributes" => "CollectionAttribute"
  }

  def find_state_of_stage(stage)
    collections_stages.to_a.each do |cs|
      return cs if cs.stage == stage
    end
    nil
  end

  def work_sets
    WorkSet.for_collection(self)
  end

  def base_collection
    @base_collection ||= if base
      self
    else
      base_collections.last || self
    end
  end

  def base_collections
    expand_with_parent_collections(:asc).not_system.where(base: true)
  end

  def super_base_collection
    base_collections.first || self
  end

  def base_collection?
    base_collection == self
  end

  def collections_stages?
    collections_stages.count > 0
  end

  def parent_collection_with_stages
    unless collections_stages?
      parent_collections_flattened.reverse_each do |coll|
        return coll if coll.collections_stages?
      end
    end
    nil
  end

  def appraise_with_ranges
    read_attribute(:appraise_with_ranges) || (self_and_parent_collections_flattened.where(appraise_with_ranges: true).count > 0)
  end
  alias_method :appraise_with_ranges?, :appraise_with_ranges

  def show_availability_status
    read_attribute(:show_availability_status) || (self_and_parent_collections_flattened.where(show_availability_status: true).count > 0)
  end
  alias_method :show_availability_status?, :show_availability_status

  def sort_works_by= value
    write_attribute(:sort_works_by, (Work::SORTING_FIELDS & [value.to_sym]).first)
  end

  def sort_works_by
    read_attribute(:sort_works_by).try(:to_sym)
  end

  def geoname_ids
    geoname_summaries.collect { |a| a.geoname_id }
  end

  def geoname_summaries?
    cached_geoname_ids && cached_geoname_ids.count > 0
  end

  def unique_short_code_from_self_or_base
    unique_short_code || base_collection.unique_short_code
  end

  def self_or_parent_collection_with_geoname_summaries
    if geoname_summaries?
      return self
    else
      parent_collections_flattened.reverse_each do |coll|
        return coll if coll.geoname_summaries?
      end
    end
    nil
  end

  def collections_stage_delivery_on
    if collections_stages.delivery.count > 0
      rv = collections_stages.delivery.first.completed_at
      rv&.to_date
    end
  end

  def collections_stage_delivery_on= date
    if collections_stages.delivery.count > 0
      collections_stage = collections_stages.delivery.first
      collections_stage.completed_at = date
      collections_stage.save
    end
  end

  def artists
    Artist.works(works_including_child_works)
  end

  def works_including_child_works
    Work.where(collection: expand_with_child_collections)
  end

  def attachments_including_child_attachments
    Attachment.where(collection: expand_with_child_collections)
  end

  def attachments_including_parent_attachments
    Attachment.where(collection: expand_with_parent_collections)
  end

  def library_items_including_child_library_items
    LibraryItem.where(collection: expand_with_child_collections)
  end

  def library_items_including_parent_library_items
    LibraryItem.where(collection: expand_with_parent_collections)
  end

  def work_attributes_present
    direct_work_attributes = Work.attributes_present
    relations = (Work.has_manies + Work.has_and_belongs_to_manies).select { |a| works.joins(a).any? }
    relations + direct_work_attributes
  end

  def derived_work_attributes_present
    direct_attributes = cached_work_attributes_present
    {
      work_status: -> { direct_attributes.include?(:work_status_id) },
      highlight: -> { direct_attributes.include?(:highlight_priority) },
      for_purchase: -> { direct_attributes.include?(:for_purchase_at) },
      for_rent: -> { direct_attributes.include?(:for_rent) },
      alt_number_4: -> { false },
      alt_number_5: -> { false },
      alt_number_6: -> { false },
      medium: -> { direct_attributes.include?(:medium_id) },
      frame_type: -> { direct_attributes.include?(:frame_type_id) },
      signature_rendered: -> { direct_attributes.include?(:signature_comments) },
      object_format_code: -> { true },
      work_size: -> { direct_attributes.include?(:height) || direct_attributes.include?(:width) },
      frame_size: -> { direct_attributes.include?(:frame_height) || direct_attributes.include?(:frame_width) },
      floor_surface: -> { direct_attributes.include?(:frame_depth) || direct_attributes.include?(:frame_width) || direct_attributes.include?(:depth) || direct_attributes.include?(:width) },
      wall_surface: -> { direct_attributes.include?(:frame_height) || direct_attributes.include?(:frame_width) || direct_attributes.include?(:height) || direct_attributes.include?(:width) },
      abstract_or_figurative_rendered: -> { direct_attributes.include?(:abstract_or_figurative) },
      style: -> { direct_attributes.include?(:style_id) },
      subset: -> { direct_attributes.include?(:subset_id) },
      collection_name_extended: -> { true },
      locality_geoname_name: -> { direct_attributes.include?(:locality_geoname_id) },
      cluster: -> { direct_attributes.include?(:cluster_id) },

app/controllers/api/v1/collections_controller.rb
class Api::V1::CollectionsController < Api::V1::ApiController
  before_action :authenticate_activated_user!
  def index
    @collections = (params[:include_children] == "true") ? @user.accessible_collections.not_root : Collection.for_user(@user).not_root.all
  end

  def show
    @collection = @user.accessible_collections.find(params[:id])
  end
end

app/controllers/collection/labels_controller.rb
# frozen_string_literal: true

class Collection::LabelsController < ApplicationController
  before_action :set_collection, only: [:index] # includes authentication

  def index
    respond_to do |format|
      format.pdf {
        labels = Collections::NumberLabels.new(
          offset: params[:offset] || 1,
          amount: params[:amount] || 16,
          collection: @collection,
          subtext: "Bij schade, verplaatsing of vragen contact opnemen met kunstzaken"
        )

        send_data labels.render
      }
    end
  end
end

app/views/collections/_collection.html.erb
<%
  parent_has_themes = defined?(parent_has_themes) ? parent_has_themes : nil
  render_themes = (defined?(render_themes) && render_themes) ? true : false
  themes = []
  if render_themes
    themes = @show_hidden ? collection.themes : collection.themes.not_hidden
  end

%>
<% cache(["collection/_collection", "1.0", collection, parent_has_themes, render_themes, @show_hidden]) do %>
<% if render_themes %>
  <% if themes.count > 0 or (defined?(parent_has_themes) && parent_has_themes) %>
    <li><%= link_to collection.name, collection_themes_path(collection, params: {show_hidden: @show_hidden}) if !collection.child_collections_flattened.include?(collection) %>
      (<%= themes.as_sentence%>)
       <ul>
  <% end %>
<% else %>
    <li><%= link_to collection.name, collection_path(collection, params: {show_hidden: @show_hidden}) if !collection.child_collections_flattened.include?(collection) %> (<%= link_to  I18n.translate('count.works', count: collection.works_including_child_works.count), collection_works_path(collection)  %><% if collection.works.count > 0 and collection.works.count != collection.works_including_child_works.count %>; in deze collectie <%= link_to  I18n.translate('count.works', count: collection.works.count), collection_works_path(collection, params: {show_hidden: @show_hidden, no_child_works: true})  %><% end %>)
       <ul>
<% end %>
  <% if collection.child_collections.count > 0 %>
    <%
    locals = {}
    locals[:render_themes] = render_themes if defined?(render_themes)
    locals[:parent_has_themes] = collection.themes.count > 0
    %>
    <%= render collection.child_collections, locals %>
  <% end %>

        </ul>
      </li>

<% end %>

app/views/collections/_manage_subnav.html.erb
<nav class="sub-nav hide-for-print" aria-label="Beheer collectie navigatie">
<ul class="menu simple">
  <li>Beheer <%=@collection.name%>:</li>
  <li><%= menu_link_to "Herinneringen", collection_reminders_path(@collection) if can? :read, Reminder %></li>
  <li><%= menu_link_to "Thema's", collection_themes_path(@collection) if can? :read, Theme %></li>
  <% if can? :read, ImportCollection.new(collection: @collection) %>
  <li><%= menu_link_to "Import", collection_import_collections_path(@collection) %></li>
  <% elsif can? :read, SimpleImportCollection.new(collection: @collection) %>
  <li><%= menu_link_to "Import", collection_simple_import_collections_path(@collection) if can? :read, SimpleImportCollection %></li>
  <% end %>
  <li><%= menu_link_to "Rapporten", collection_custom_reports_path(@collection) if can? :review_collection, CustomReport %></li>
  <li><%= menu_link_to "Gebruikers", collection_users_path(@collection) if can? :review_collection_users, @collection %></li>

</ul>
</nav>

app/views/collections/_subnav.html.erb
<nav class="sub-nav hide-for-print" aria-label="Collectienavigatie">

<ul class="menu simple left hide-for-small-only">

  <li><strong><%= menu_link_to @collection.name, collection_path(@collection), only_exact_path_match: true %>:</strong></li>
  <% unless can?(:review_collection_users, @collection) || can?(:review, @collection) %>
  <li><%= menu_link_to "Overzicht", collection_path(@collection), only_exact_path_match: true %></li>
  <% end %>
  <li><%= menu_link_to "Werken", collection_works_path(@collection)%></li>
  <% if can? :read_report, @collection %>
  <li><%= menu_link_to "Rapportage", collection_report_path(@collection) %></li>
  <% end %>
  <% if can? :read, Artist %>
  <li><%= menu_link_to "Vervaardigers", collection_artists_path(@collection) %></li>
  <% end %>
  <% if can?(:read, LibraryItem) && @collection.show_library? %>
  <li><%= menu_link_to "Bibliotheek", collection_library_items_path(@collection) %></li>
  <% end %>
  <% if can? :review_collection, Cluster%>
  <li><%= menu_link_to "Clusters", collection_clusters_path(@collection) %></li>
  <% end %>
  <% if can?(:review_modified_works, @collection) && !(can?(:review_collection_users, @collection) || can?(:review, @collection)) %>
  <li><%= menu_link_to "Recent gewijzigd", collection_works_modified_path(@collection) %></li>
  <% end %>
  <% if can?(:review_collection_users, @collection) || can?(:review, @collection) %>
  <li><%= menu_link_to "Beheer", collection_manage_path(@collection) %></li>
  <% end %>
</ul>

<ul class="menu right-aligned menu--only-buttons">
  <% if can? :create, @collection.works.new %>
    <li><%= link_to "+ Voeg werk toe", new_collection_work_path(@collection), class: 'small button' %></li>
  <% end %>


  <% if can? :create, @collection.messages.new %>
    <% messages_url = (@work && @work.id) ? collection_work_messages_path(@collection, @work) : collection_messages_path(@collection) %>
    <% _messages = (@work && @work.id) ? @work.messages : @collection.messages %>
    <% _messages = _messages.conversation_starters.thread_can_be_accessed_by_user(current_user) %>
    <% messages_count = _messages.count %>
    <li>
      <%= link_to messages_url, class: qkunst_user? ? 'secondary small button' : 'small button', data: { open_in_context: true} do %>
        Vraag of opmerking?
        <% if messages_count > 0 %>
          <span class="badge"><%=messages_count%></span>
        <% end %>
      <% end %>
    </li>
  <% end %>
  <% if can? :batch_edit, @collection %>
    <li><%= link_to "Scan", collection_batch_path(@collection), class: 'small button secondary' %></li>
  <% end %>

  <li>
    <%= form_tag collection_works_path(@collection), method: :get, authenticity_token: false, data: {auto_submit: true} do %>
      <%= text_field_tag :q, @search_text, type: :search, placeholder: "Zoek... ", title: "Zoek hier", class: "input-group-field"%>
    <% end %>
  </li>


</ul>
</nav>

app/views/collections/edit.html.erb
<h2>Bewerk deze collectie</h2>

<%= render 'form' %>

<%= link_to 'Wijzigingen niet opslaan', @collection %>

app/views/collections/manage.html.erb
<h2>Beheer collectie specifieke opties</h2>

<p>
  <%= button_to 'Ververs rapportage', collection_refresh_works_path(@collection), method: :post, class: [:button, :tertiary, :small], title: "Afhankelijk van de hoeveelheid werken in dit collectie kan dit soms lang duren." if can? :refresh, @collection%>
</p>
<ul>
  <%= menu_link_to("Eigenaren", collection_owners_path(@collection), {wrap: :li}) if can? :review_collection, Owner %>
  <%= menu_link_to("Gebruikers", collection_users_path(@collection), {wrap: :li}) if can? :review_collection_users, @collection %>
  <%= menu_link_to("Groeperingen", collection_work_sets_path(@collection), {wrap: :li}) if can? :edit, @collection %>
  <%= menu_link_to("Herinneringen", collection_reminders_path(@collection), {wrap: :li}) if can? :review_collection, Reminder %>
  <%= menu_link_to("Attribuut Import", collection_simple_import_collections_path(@collection), {wrap: :li}) if can? :review_collection, SimpleImportCollection.new(collection: @collection) %>
  <%= menu_link_to("Import", collection_import_collections_path(@collection), {wrap: :li}) if can? :review_collection, ImportCollection.new(collection: @collection) %>
  <%= menu_link_to("Locaties", collection_locations_path(@collection), {wrap: :li}) if can? :review_collection, ImportCollection.new(collection: @collection) %>
  <%= menu_link_to("Rapporten", collection_custom_reports_path(@collection), {wrap: :li}) if can? :review_collection, CustomReport.new(collection: @collection) %>
  <%= menu_link_to("Recent gewijzigd", collection_works_modified_path(@collection), {wrap: :li}) if can?(:review_modified_works, @collection) %>
  <%= menu_link_to("Thema's", collection_themes_path(@collection), {wrap: :li}) if can? :review_collection, Theme %>
</ul>

app/views/collections/new.html.erb
<h2>Maak een nieuwe collectie</h2>
<p>Geef de collectie een naam.</p>
<%= render 'form' %>

<%= link_to 'Terug naar overzicht', collections_path %>

app/views/collections/show.html.erb
<header class="row">
  <div class="large-12 columns">
    <% if @collection.parent_collection && !@collection.parent_collection.system? %>
      Maakt deel uit van:
      <%= sanitize @collection.parent_collections_flattened.collect{|a| a.can_be_accessed_by_user(current_user) ? link_to(a.name,a) : a.name}.join(" &raquo; ")%>
    <% end %>

    <h1><%= @collection.name %></h1>
    <%= kramdown( @collection.description) %>

  </div>

</header>
<nav class="sub-nav bottom-nav hide-for-print" aria-label="Collectie-acties">
  <ul class="menu right-aligned menu--only-buttons">
    <% if can?(:edit, @collection) %>
      <%= link_to 'Bewerk gegevens', edit_collection_path(@collection), class: 'primary small button' %>
    <% end %>
  </ul>
</nav>

<div class="row">
<div class="large-9 medium-9 columns">
<%= render :partial => 'collection_stages_graph' %>

<h3>Werken</h3>
<%= form_tag collection_works_path(@collection), method: :get, authenticity_token: false, data: {auto_submit: true}, class: [:secondary, :callout] do %>
<label for="q">Doorzoek de werken:</label>
<div class="input-group">
  <%= text_field_tag :q, @search_text, type: :search, placeholder: "Zoeken... ", class: "input-group-field"%>
  <div class="input-group-button">
  <%= submit_tag("Zoeken", class: :button)%>
  </div>
</div>
<p class="hint"><small>Probeer ook eens: <%=["“wildc*rd”", "“één OR ander”", "“\"exacte match\"”", "“fuzzy~”"].sample(2).join(" of ")%></small></p>
<% end %>

<div class="row">
  <div class="large-12 columns">
<%= render @collection.works_including_child_works.order(grade_within_collection: :asc, market_value: :desc)[0..3]%>
  </div>
</div>
<p><%= link_to "Toon alle #{@collection.works_including_child_works.count} werken", collection_works_path(@collection) %></p>
<% if @collection.internal_comments? and qkunst_user? %>
<h3>Interne opmerkingen</h3>
<%= kramdown(@collection.internal_comments) %>
<% end %>
  <h3>Subcollecties</h3>
  <% if @collections.count > 0 %>
    <ul>
      <%= render @collections%>
    </ul>
  <% else %>
  <p>Deze collectie kent geen subcollecties.</p>
  <% end %>
  <%= link_to 'Voeg nieuwe subcollectie voor deze collectie toe', new_collection_collection_path(@collection) if can? :create, @collection.collections.new%>

</div>

<% if can?(:create, @collection.attachments.new) or @collection.attachments.for_me(current_user).count > 0 %>
<aside class="large-3 medium-3 columns" style="margin-top: 1em">
  <h3>Bijlagen</h3>
  <ul>
    <% @attachments.each do |attachment| %>
      <li><%= link_to attachment.file_name.truncate(30, omission: "…#{attachment.file_name.last(15)}"), attachment.file.url, title: attachment.file_name, download: attachment.file_name %> <small>(<%= number_to_human_size(attachment.file.size)%>)</small></li>
    <% end %>
  </ul>
  <% if can? :create, @collection.attachments.new %>
    <p><%= link_to 'Beheer bijlagen', collection_attachments_path(@collection) %></p>
  <% end %>
  <% if @collection.external_reference_code? %>
  <p><strong>Referentiecode:</strong><%=@collection.external_reference_code%></p>
  <% end %>
</aside>
<% end %>
</div>

app/views/collections/themes.html.erb
<div class="row">
  <div class="large-9 columns">
    <h2>Thema's binnen <%=@collection.name%></h2>
    <div class="row">
      <div class="large-4 columns">
        <h4>Algemeen</h4>
        <ul>
          <%= render Theme.general.all %>
        </ul>
      </div>
      <div class="large-4 columns">
        <h4>Uit bovenliggende collecties</h4>
        <% if @collection.parent_collections_flattened.count > 0 %>
          <% count = 0 %>
          <% @collection.parent_collections_flattened.each do |collection| %>
            <% if collection.themes.show_hidden(@show_hidden).count > 0 %>
              <h6><%= collection.name%></h6>
              <ul>
                <%= render collection.themes %>
                <% count += 1%>
              </ul>
            <% end %>
          <% end %>
          <% if count == 0 %>
            <p>Deze deelcollectie heeft geen thema's overgekregen uit bovenliggende collecties</p>
          <% end%>
        <% else %>
          <p>Dit is geen deelcollectie</p>
        <% end %>
      </div>
      <div class="large-4 columns">
        <h4>Collectiespecifiek</h4>
        <ul>
          <%= render @collection.themes %>
        </ul>
      </div>
    </div>


  </div>
  <aside class="large-3 columns">
    <%= link_to 'Nieuw collectie-thema', new_collection_theme_path(@collection), class: 'button' if can? :create, @collection.themes.new %>
    <% if @show_hidden %>
      <p>Verborgen thema's worden nu weergegeven, <%= link_to "verberg de verborgen thema's", collection_themes_path(@collection, show_hidden: nil)%></p>
    <% else %>
      <p>Verborgen thema's zijn nu verborgen, <%= link_to "toon ook deze thema's", collection_themes_path(@collection, show_hidden: true)%></p>
    <% end %>
  </aside>
</div>