config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  get "short_code_resolver/resolve/:collection_code/:work_code" => "short_code_resolver#resolve"
  get "application_status" => "status#application_status"

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :custom_report_templates
  get "tags.json" => "application#tags"
  get "geoname_summaries.json" => "application#geoname_summaries"

  resources :reminders
  resources :stages
  get "offline/work_form"

  get "offline/offline"

  get "offline/collections"

  get "offline/collection"

  get "scan" => "scan#show"

  namespace :api do
    namespace :v1 do
      resources :time_spans, only: [:index, :show]
      resources :works, only: [:show]
      resources :work_sets, only: [:show]
      resources :collections, only: [:index, :show] do
        resources :works, only: [:index, :show] do
          resources :work_events, only: [:create]
        end
      end
    end
  end

  resources :messages do
    get "new_reply" => "messages#new"
  end
  devise_for :users, controllers: {
    confirmation: "confirmation",
    registrations: "registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }
  resources :users, only: [:index, :edit, :update, :destroy]
  get "users/oauth"

  resources :conditions
  resources :currencies
  resources :damage_types
  resources :frame_damage_types
  resources :frame_types
  resources :media
  resources :object_categories
  resources :placeabilities
  resources :sources
  resources :subsets
  resources :techniques
  resources :themes
  resources :balance_categories
  resources :work_statuses
  resources :work_sets do
    resources :works, module: :work_sets, only: :destroy # , controller: "WorkSet::WorksController"
  end
  resources :work_set_types

  resources :rkd_artists, module: :r_k_d, controller: :artists do
    patch "copy" => "rkd_artists#copy"
  end

  resources :works do
    resources :attachments
  end

  resources :involvements
  resources :collections do
    get "manage" => "collections#manage"
    resources :contacts
    resources :locations
    resources :users, module: :collection
    resources :labels, module: :collection
    resources :library_items
    resources :time_spans, only: [:index, :show]

    resources :work_sets do
      resources :appraisals
      resources :time_spans
    end

    resources :reminders, path: "manage/reminders"
    resources :themes, path: "manage/themes"
    resources :clusters
    resources :import_collections, path: "manage/import_collections" do
      get "preview" => "import_collections#preview"
      patch "delete_works" => "import_collections#delete_works"
      patch "import_works" => "import_collections#import_works"
    end

    resources :simple_import_collections, path: "manage/simple_import_collections" do
      get "preview" => "simple_import_collections#preview"
      patch "import_works" => "simple_import_collections#import_works"
    end

    resources :owners
    resources :custom_reports, path: "manage/custom_reports"

    resources :attachments
    resources :collections_stages
    resources :messages
    post "refresh_works" => "collections#refresh_works"
    resources :collections do
    end
    resources :batch_photo_uploads do
      post "match_works" => "batch_photo_uploads#match_works"
    end
    resources :artists do
      get :collectie_nederland_summary

      get "combine_prepare" => "artists#combine_prepare"
      patch "combine" => "artists#combine"

      resources :rkd_artists, module: :r_k_d, controller: :artists
      resources :artist_involvements
      resources :attachments
      resources :library_items
    end
    resources :rkd_artists, module: :r_k_d, controller: :artists do
      patch "copy" => "rkd_artists#copy"
    end

    get "works/modified" => "works#modified_index"

    get "batch" => "batch#show"
    post "batch" => "batch#show"
    patch "batch" => "batch#update"

    get "mobile" => "mobiles#show"
    patch "mobile" => "mobiles#update"

    resources :works do
      resources :attachments
      resources :appraisals
      resources :messages
      resources :library_items
      resources :time_spans
      get "old_data" => "works#show_old_data"
      get "edit_prices" => "works#edit_prices"
      get "location_history" => "works#location_history"
      get "edit_location" => "works#edit_location"
      get "edit_tags" => "works#edit_tags"
      get "edit_photos" => "works#edit_photos"
    end

    get "report" => "report#show"
    get "stats" => "stats#show"
  end
  resources :artists do
    get :collectie_nederland_summary
    patch "collectie_nederland_summary" => "artists#collectie_nederland_summary_update"
    get "combine_prepare" => "artists#combine_prepare"
    patch "combine" => "artists#combine"
    resources :rkd_artists, module: :r_k_d, controller: :artists
    get "old_data" => "artists#show_old_data"

    resources :artist_involvements
  end
  post "/artists/clean" => "artists#clean"

  resources :professional_activities

  get "debug-offline" => "application#debug_offline"

  get "admin", to: Admin::AdminController.action(:index)

  namespace :admin do
    resources :o_auth_group_mappings
  end
  get "sw" => "application#service_worker"
  get "style-guide" => "application#style_guide"
  root "application#home"

end

app/models/custom_report.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: custom_reports
#
#  id                        :bigint           not null, primary key
#  html_cache                :string
#  title                     :string
#  variables                 :string
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  collection_id             :bigint
#  custom_report_template_id :bigint
#
class CustomReport < ApplicationRecord
  belongs_to :collection
  belongs_to :custom_report_template
  has_and_belongs_to_many :works

  validates_presence_of :collection, :custom_report_template

  store :variables

  def template_fields
    custom_report_template.fields
  end

  def title
    tmp = read_attribute(:title)
    if tmp.nil? || (tmp == "")
      [custom_report_template.name, I18n.l(created_at.to_date, format: :long)].join(", ")
    else
      tmp
    end
  end
  alias_method :name, :title

  def title_with_collection
    [collection.name, title].compact.join(": ")
  end

  def merged_content
    custom_report_template.content_merge(variables)
  end
end

app/controllers/custom_reports_controller.rb
# frozen_string_literal: true

class CustomReportsController < ApplicationController
  include Works::WorkIds

  before_action :set_collection
  before_action :set_custom_report, only: [:show, :edit, :update, :destroy]

  # GET /custom_reports
  # GET /custom_reports.json
  def index
    authorize! :index, CustomReport
    @custom_reports = @collection.custom_reports.all
  end

  # GET /custom_reports/1
  # GET /custom_reports/1.json
  def show
    authorize! :show, CustomReport
  end

  # GET /custom_reports/new
  def new
    authorize! :new, CustomReport
    @custom_report = @collection.custom_reports.new
    @works = set_works_by_work_ids_or_work_ids_hash
    @custom_report.works = @collection.works_including_child_works.where(id: @works)
  end

  # GET /custom_reports/1/edit
  def edit
    authorize! :edit, CustomReport
  end

  # POST /custom_reports
  # POST /custom_reports.json
  def create
    authorize! :create, CustomReport

    @custom_report = CustomReport.new(custom_report_params)
    @custom_report.collection = @collection
    respond_to do |format|
      if @custom_report.save
        format.html { redirect_to edit_collection_custom_report_path(@collection, @custom_report), notice: "Rapport is gemaakt, vul de variabelen aan" }
        format.json { render :show, status: :created, location: @custom_report }
      else
        format.html { render :new }
        format.json { render json: @custom_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_reports/1
  # PATCH/PUT /custom_reports/1.json
  def update
    authorize! :update, CustomReport

    respond_to do |format|
      if @custom_report.update(custom_report_params)
        format.html { redirect_to [@collection, @custom_report], notice: "Custom report was successfully updated." }
        format.json { render :show, status: :ok, location: @custom_report }
      else
        format.html { render :edit }
        format.json { render json: @custom_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_reports/1
  # DELETE /custom_reports/1.json
  def destroy
    authorize! :destroy, CustomReport

    @custom_report.destroy
    respond_to do |format|
      format.html { redirect_to collection_custom_reports_url(@collection), notice: "Custom report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_custom_report
    @custom_report = @collection.custom_reports.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def custom_report_params
    allowed_variables = @custom_report ? @custom_report.template_fields : []

    params.require(:custom_report).permit(:custom_report_template_id, :title, work_ids: [], variables: allowed_variables)
  end
end

app/views/custom_reports/_custom_report_rendered.html.erb
    <div class="preview-a4" style="<%=defined?(style) ? style : nil%>">
      <%= sanitize @custom_report.merged_content.gsub("{{@works}}", "<div class=\"row columns\">#{render(@custom_report.works)}</div>") %>
    </div>

app/views/custom_reports/_form.html.erb
<div class="row">
  <div class="medium-6 columns">
  <%= simple_form_for([@collection, @custom_report]) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <!-- <%= f.association :custom_report_template %> -->
      <%= f.input :title %>
      <hr/>
      <% @custom_report.template_fields.each do |field_name| %>
        <label>
          <%= field_name.capitalize.gsub('_',' ') %>
          <%= text_field_tag "custom_report[variables][#{field_name}]", @custom_report.variables[field_name]%>
        </label>
      <% end %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: :button %>
    </div>
  <% end %>
  </div>
  <div class="medium-6 columns" style="overflow: scroll">
    <%= render partial: 'custom_report_rendered', locals: { style: "transform: scale(0.5); transform-origin: top left" } %>
  </div>

</div>

app/views/custom_reports/_index.html.erb
<table>
  <thead>
    <tr>
      <th>Aangemaakt op</th>
      <th>Template</th>
    </tr>
  </thead>

  <tbody>
    <% @custom_reports.each do |custom_report| %>
      <tr>
        <td><%= link_to (I18n.l custom_report.created_at, format: :long), [custom_report.collection, custom_report] %></td>
        <td><%= link_to custom_report.custom_report_template.title, [custom_report.collection, custom_report] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/custom_reports/edit.html.erb
<h2>Bewerk</h2>

<%= render 'form', custom_report: @custom_report %>

<%= link_to 'Show', [@collection, @custom_report] %>

app/views/custom_reports/index.html.erb
<div class="row">
  <div class="large-9 medium-9 columns">

<h2>Opgeslagen rapportages</h2>

<%= render partial: 'index' %>
</div>
  <aside class="large-3 medium-3 columns">
    <%= link_to 'Maak rapportage', new_collection_custom_report_path(@collection), class: :button %>
  </aside>
</div>

app/views/custom_reports/new.html.erb
<h2>Maak een nieuwe rapportage</h2>

<%= simple_form_for([@collection, @custom_report]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :custom_report_template %>
    <div style="<%= "display:none" if @custom_report.works.to_a.count > 0 %>">
      <%= f.association :works, collection: @collection.works_including_child_works %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: :button %>
  </div>
<% end %>

<%= link_to 'Terug', collection_custom_reports_path(@collection) %>

app/views/custom_reports/show.html.erb
<div class="row">
  <div class="medium-9 columns">
    <%= render partial: 'custom_report_rendered'%>
  </div>
  <aside class="medium-3 columns">
    <%= link_to 'Verstuur link', "mailto:?subject=#{@custom_report.title}&body=#{url_encode("Geachte heer, mevrouw,\n\nEr staat een rapport voor u klaar. Open het rapport door te klikken op de volgende link:\n#{collection_custom_report_url(@collection, @custom_report)}")}", class: :button %>
    <%= link_to 'Download PDF', collection_custom_report_path(@collection, @custom_report), class: [:secondary, :button] %>
    <%= link_to 'Bewerk', edit_collection_custom_report_path(@collection, @custom_report), class: [:secondary, :button] %>
    <% if @custom_report.variables.count > 0 %>
      <h5>Variabelen</h5>
      <dl>
      <% @custom_report.variables.each do |k,v| %>
        <dt><%=sanitize k%></dt><dd><%=sanitize v%></dd>
      <% end %>
      </dl>
    <% end %>
    <p>Template: <%= link_to @custom_report.custom_report_template.title, edit_custom_report_template_path(@custom_report.custom_report_template) %></p>
  </aside>
</div>